# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E3E9EF
background         #1B1E26
cursor             #8CC0D6

active_tab_foreground     #1B1E26
active_tab_background     #E3E9EF
inactive_tab_foreground   #E3E9EF
inactive_tab_background   #1B1E26

active_border_color   #E3E9EF
inactive_border_color #1B1E26
bell_border_color     #262B35

color0      #1B1E26
color1		#262B35
color2		#AACCDD
color3		#CCB2B9
color4		#6A96A3
color5		#3B3440
color6		#8CC0D6
color7		#E3E9EF
color8		#8A919C
color9		#313845
color10		#6A96A3
color11		#C99AA0
color12		#8CC0D6
color13		#D69CAC
color14		#AACCDD
color15		#E3E9EF
