# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(EEF2F6)
$foreground = rgb(30343D)
$color0 = rgb(EEF2F6)
$color1 = rgb(DDE6EE)
$color2 = rgb(AACCDD)
$color3 = rgb(CCB2B9)
$color4 = rgb(9CB9C9)
$color5 = rgb(D9C3CE)
$color6 = rgb(4F7C8B)
$color7 = rgb(30343D)
$color8 = rgb(767C85)
$color9 = rgb(C8D6E0)
$color10 = rgb(9CB9C9)
$color11 = rgb(B98A8F)
$color12 = rgb(4F7C8B)
$color13 = rgb(926675)
$color14 = rgb(AACCDD)
$color15 = rgb(30343D)
