# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1E26)
$foreground = rgb(E3E9EF)
$color0 = rgb(1B1E26)
$color1 = rgb(262B35)
$color2 = rgb(AACCDD)
$color3 = rgb(CCB2B9)
$color4 = rgb(6A96A3)
$color5 = rgb(3B3440)
$color6 = rgb(8CC0D6)
$color7 = rgb(E3E9EF)
$color8 = rgb(8A919C)
$color9 = rgb(313845)
$color10 = rgb(6A96A3)
$color11 = rgb(C99AA0)
$color12 = rgb(8CC0D6)
$color13 = rgb(D69CAC)
$color14 = rgb(AACCDD)
$color15 = rgb(E3E9EF)
